### ISSUE TITLE
UTF-8 Encoding 

### ISSUE THREAD

**Issue by p021918** [PredixDev/data-seed-service#3]
Dear

I uploaded a asset model data file as json format which has Korean characters. It's loaded successfully, but it's broken as ??? when it's queried from Asset API via Postman rest client.

Please guide how to fix or adjust the code for handling double-byte character . many thanks

**Comment by swapnavad** [comment]
This is requires a change on the asset-bootstrap SDK. We have added this request to our backlog and will address it shortly.
